export const hiragana = [
  { char: 'あ', romaji: 'a', korean: '아' },
  { char: 'い', romaji: 'i', korean: '이' },
  { char: 'う', romaji: 'u', korean: '우' },
  { char: 'え', romaji: 'e', korean: '에' },
  { char: 'お', romaji: 'o', korean: '오' },
  { char: 'か', romaji: 'ka', korean: '카' },
  { char: 'き', romaji: 'ki', korean: '키' },
  { char: 'く', romaji: 'ku', korean: '쿠' },
  { char: 'け', romaji: 'ke', korean: '케' },
  { char: 'こ', romaji: 'ko', korean: '코' },
  { char: 'さ', romaji: 'sa', korean: '사' },
  { char: 'し', romaji: 'shi', korean: '시' },
  { char: 'す', romaji: 'su', korean: '스' },
  { char: 'せ', romaji: 'se', korean: '세' },
  { char: 'そ', romaji: 'so', korean: '소' },
  { char: 'た', romaji: 'ta', korean: '타' },
  { char: 'ち', romaji: 'chi', korean: '치' },
  { char: 'つ', romaji: 'tsu', korean: '츠' },
  { char: 'て', romaji: 'te', korean: '테' },
  { char: 'と', romaji: 'to', korean: '토' },
  { char: 'な', romaji: 'na', korean: '나' },
  { char: 'に', romaji: 'ni', korean: '니' },
  { char: 'ぬ', romaji: 'nu', korean: '누' },
  { char: 'ね', romaji: 'ne', korean: '네' },
  { char: 'の', romaji: 'no', korean: '노' },
  { char: 'は', romaji: 'ha', korean: '하' },
  { char: 'ひ', romaji: 'hi', korean: '히' },
  { char: 'ふ', romaji: 'fu', korean: '후' },
  { char: 'へ', romaji: 'he', korean: '헤' },
  { char: 'ほ', romaji: 'ho', korean: '호' },
  { char: 'ま', romaji: 'ma', korean: '마' },
  { char: 'み', romaji: 'mi', korean: '미' },
  { char: 'む', romaji: 'mu', korean: '무' },
  { char: 'め', romaji: 'me', korean: '메' },
  { char: 'も', romaji: 'mo', korean: '모' },
  { char: 'や', romaji: 'ya', korean: '야' },
  { char: 'ゆ', romaji: 'yu', korean: '유' },
  { char: 'よ', romaji: 'yo', korean: '요' },
  { char: 'ら', romaji: 'ra', korean: '라' },
  { char: 'り', romaji: 'ri', korean: '리' },
  { char: 'る', romaji: 'ru', korean: '루' },
  { char: 'れ', romaji: 're', korean: '레' },
  { char: 'ろ', romaji: 'ro', korean: '로' },
  { char: 'わ', romaji: 'wa', korean: '와' },
  { char: 'を', romaji: 'wo', korean: '오(wo)' },
  { char: 'ん', romaji: 'n', korean: '응(n)' },
];

export const katakana = [
  { char: 'ア', romaji: 'a', korean: '아' },
  { char: 'イ', romaji: 'i', korean: '이' },
  { char: 'ウ', romaji: 'u', korean: '우' },
  { char: 'エ', romaji: 'e', korean: '에' },
  { char: 'オ', romaji: 'o', korean: '오' },
  { char: 'カ', romaji: 'ka', korean: '카' },
  { char: 'キ', romaji: 'ki', korean: '키' },
  { char: 'ク', romaji: 'ku', korean: '쿠' },
  { char: 'ケ', romaji: 'ke', korean: '케' },
  { char: 'コ', romaji: 'ko', korean: '코' },
  { char: 'サ', romaji: 'sa', korean: '사' },
  { char: 'シ', romaji: 'shi', korean: '시' },
  { char: 'ス', romaji: 'su', korean: '스' },
  { char: 'セ', romaji: 'se', korean: '세' },
  { char: 'ソ', romaji: 'so', korean: '소' },
  { char: 'タ', romaji: 'ta', korean: '타' },
  { char: 'チ', romaji: 'chi', korean: '치' },
  { char: 'ツ', romaji: 'tsu', korean: '츠' },
  { char: 'テ', romaji: 'te', korean: '테' },
  { char: 'ト', romaji: 'to', korean: '토' },
  { char: 'ナ', romaji: 'na', korean: '나' },
  { char: 'ニ', romaji: 'ni', korean: '니' },
  { char: 'ヌ', romaji: 'nu', korean: '누' },
  { char: 'ネ', romaji: 'ne', korean: '네' },
  { char: 'ノ', romaji: 'no', korean: '노' },
  { char: 'ハ', romaji: 'ha', korean: '하' },
  { char: 'ヒ', romaji: 'hi', korean: '히' },
  { char: 'フ', romaji: 'fu', korean: '후' },
  { char: 'ヘ', romaji: 'he', korean: '헤' },
  { char: 'ホ', romaji: 'ho', korean: '호' },
  { char: 'マ', romaji: 'ma', korean: '마' },
  { char: 'ミ', romaji: 'mi', korean: '미' },
  { char: 'ム', romaji: 'mu', korean: '무' },
  { char: 'メ', romaji: 'me', korean: '메' },
  { char: 'モ', romaji: 'mo', korean: '모' },
  { char: 'ヤ', romaji: 'ya', korean: '야' },
  { char: 'ユ', romaji: 'yu', korean: '유' },
  { char: 'ヨ', romaji: 'yo', korean: '요' },
  { char: 'ラ', romaji: 'ra', korean: '라' },
  { char: 'リ', romaji: 'ri', korean: '리' },
  { char: 'ル', romaji: 'ru', korean: '루' },
  { char: 'レ', romaji: 're', korean: '레' },
  { char: 'ロ', romaji: 'ro', korean: '로' },
  { char: 'ワ', romaji: 'wa', korean: '와' },
  { char: 'ヲ', romaji: 'wo', korean: '오(wo)' },
  { char: 'ン', romaji: 'n', korean: '응(n)' },
];

export const allCharacters = [
  ...hiragana.map(c => ({ ...c, type: 'hiragana' })),
  ...katakana.map(c => ({ ...c, type: 'katakana' }))
];
